management:
  health:
    diskspace:
      enabled: 'true'
    default:
      enabled: 'true'
    db:
      enabled: 'true'
  servlet:
    context-path: /manage
    
spa:
  default-file: /dist/index.html
  
spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: 'true'
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: ssafyb202t
      username: friendject
    url: jdbc:mysql://54.180.140.55:3307/friendject?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  
  data:
    web:
      pageable:
        one-indexed-parameters: 'true'
  
  http:
    multipart:
      enabled: 'false'
      
  mvc:
    throw-exception-if-no-handler-found: 'true'
    
  devtools:
    livereload:
      enabled: 'true'
      
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      
  resources:
    static-locations: classpath:/dist/
    add-mappings: 'false'
    
logging:
  level:
    org:
      sringframework:
        boot: DEBUG
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
    root: INFO
    
server:
  port: 8081
  compression:
    enabled: 'true'
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

build:
  date: '@build.date@'
  
jwt:
  expiration: '1296000000'
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'
